### ISSUE TITLE
Need for your kindly help with code problem

### ISSUE THREAD

**Issue by GuokaiLiu** [udibr/noisy_labels#2]
Hello Udibr,
Thanks for sharing your great work with the **noisy_labels**.
I'm now doing a relevant research on the noisy data problem.
[Noisy-Labels-Problem-Collection](https://github.com/GuokaiLiu/Noisy-Labels-Problem-Collection)
and find your amazing code.

I have a question that how should I run your 161103, 161202 and 161230 Jupyter notebook code?
# 1  
When I run it, the following comes out:
 [Errno 2] No such file or directory: 'data/160919-run-plot.results.pkl'
# 2 
When I execute `bash run_all.bash`, the following comes out:
name 'basestring' is not defined
# 3
How can I get the data folder and get the above three jupyter notebooks to run rightly?

---
**I wish you could kindly help me since I'm doing my master's thesis and being in a puzzle about it for a long time**.

Thank you very much!
Looking forward to your reply : ）

**Comment by udibr** [comment]
for the `basestring` error I'm guessing you are using python3 and I was using python 2.7.

**Comment by udibr** [comment]
The file 160919-run-plot is created by running run.bash commands with --FN=160919-run-plot as one of the parameters. See the commented out lines in the 3rd cell of https://github.com/udibr/noisy_labels/blob/master/161103-run-plot.ipynb

**Comment by udibr** [comment]
Please let me know if you need any more help and if you get any results on your data set.

**Comment by GuokaiLiu** [comment]
Hi, Udibr,
Sincerely thanks for your reply.
I have changed to use python 2.7 today according to your insightful suggestion and get some data, here is the result.
[jupyter notebook](https://github.com/GuokaiLiu/Noisy-Labels-Problem-Collection/blob/master/Materials/161103-run-plot2.ipynb) .

Some errors might be caused by the packages. So could you please describe your configures?
Such as:
1. Linux/Windows/MacOS?
2. tenforflow and keras version?
---
And in order to get all the plot data in  
https://github.com/udibr/noisy_labels/blob/master/161103-run-plot.ipynb
Should I run the code one by one?

```
# ./run.bash --FN=data/$1
# ./run.bash --FN=data/$1 --model=simple --beta=0
# ./run.bash --FN=data/$1 --model=complex --beta=0 --pretrain=2
# ./run.bash --FN=data/$1 --model=reed_hard --beta=0.8
# ./run.bash --FN=data/$1 --model=reed_soft --beta=0.95
```

Thank you very much! ： ）
Best Regards!

**Comment by udibr** [comment]
Youre run looks great. Don’t see any error happening in it.
If you run all the steps one by one you should get all graphs at the end

**Comment by GuokaiLiu** [comment]
Hello,  Udibr,
Thank you for your tireless answers. 
Final results come out of trial and error for me in these days.
[161103-run-plot4](https://github.com/GuokaiLiu/Noisy-Labels-Problem-Collection/blob/master/Materials/161103-run-plot4.ipynb)

Here remains one problem to be solved.
Due to the limited Nvidia GPU 1080Ti display memory, 
it seems that I can only run one seed of five to avoid out of memory.
I think there may exist some tricks or settings to solve the problem.

**Running Environment Configuration**:

- Linux 16.04
- Anaconda 3 (create an environment with python 2.7)
- tensorflow=1.2.0
- keras=1.2.2
- theano=0.9
- keras.json: tensorflow→theano



**Looking forward to your wonderful post-sharing.**
With all my best wishes!
Guokai
